# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-01-23 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190118_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='projects.Project'),
        ),
    ]
