# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-01-06 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181230_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
