# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-01-06 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190106_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='projects.Position'),
        ),
    ]
