# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-01-18 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='skill',
            field=models.ManyToManyField(default='', related_name='skills', to='accounts.Skill'),
        ),
    ]
